/** Measurement lists carried over verbatim from api/porsche/vehicle/[vin]/*.js */

/** The poller's single call: position, odometer, battery and charging together. */
export const OVERVIEW_MEASUREMENTS = [
  'BATTERY_LEVEL', 'E_RANGE', 'MILEAGE', 'GPS_LOCATION',
  'CHARGING_SUMMARY', 'CHARGING_RATE', 'LOCK_STATE_VEHICLE',
] as const;
// NOTE: BATTERY_CHARGING_STATE is NOT a real key — requested against the live
// car it came back absent entirely, not even as isEnabled:false (#15 probe).
// Charging state comes from CHARGING_SUMMARY.status ("NOT_PLUGGED" etc.).

export const TRIP_MEASUREMENTS = [
  'TRIP_STATISTICS_CYCLIC',
  'TRIP_STATISTICS_LONG_TERM',
  'TRIP_STATISTICS_LONG_TERM_HISTORY',
  'TRIP_STATISTICS_SHORT_TERM_HISTORY',
  'TRIP_STATISTICS_CYCLIC_HISTORY',
  'TRIP_STATISTICS_SHORT_TERM',
] as const;

// NOTE: TRIP_STATISTICS_MONTHLY_REPORT is deliberately NOT in the list above.
// Probed live on 2026-08-22 (#15): the key is recognised — it comes back in the
// response — but with `isEnabled: false` and no value. So there is no
// server-side monthly aggregation to lean on; the monthly figure is ours to
// compute (#14). Re-add only if a probe ever shows it enabled.

export const ALL_MEASUREMENTS = [
  'BATTERY_LEVEL', 'BATTERY_CHARGING_STATE', 'E_RANGE', 'RANGE',
  'CHARGING_SUMMARY', 'CHARGING_RATE', 'CHARGING_PROFILES', 'CHARGING_SETTINGS',
  'MILEAGE', 'GPS_LOCATION', 'LOCK_STATE_VEHICLE', 'PARKING_BRAKE', 'PARKING_LIGHT',
  'OPEN_STATE_DOOR_FRONT_LEFT', 'OPEN_STATE_DOOR_FRONT_RIGHT',
  'OPEN_STATE_DOOR_REAR_LEFT', 'OPEN_STATE_DOOR_REAR_RIGHT',
  'OPEN_STATE_LID_FRONT', 'OPEN_STATE_LID_REAR',
  'OPEN_STATE_WINDOW_FRONT_LEFT', 'OPEN_STATE_WINDOW_FRONT_RIGHT',
  'OPEN_STATE_WINDOW_REAR_LEFT', 'OPEN_STATE_WINDOW_REAR_RIGHT',
  'OPEN_STATE_SUNROOF', 'OPEN_STATE_SUNROOF_REAR', 'OPEN_STATE_TOP', 'OPEN_STATE_SPOILER',
  'OPEN_STATE_CHARGE_FLAP_LEFT', 'OPEN_STATE_CHARGE_FLAP_RIGHT', 'OPEN_STATE_SERVICE_FLAP',
  'TIRE_PRESSURE',
  'CLIMATIZER_STATE', 'HEATING_STATE', 'HVAC_STATE',
  'MAIN_SERVICE_RANGE', 'MAIN_SERVICE_TIME',
  'INTERMEDIATE_SERVICE_RANGE', 'INTERMEDIATE_SERVICE_TIME',
  'OIL_SERVICE_RANGE', 'OIL_SERVICE_TIME',
  'OIL_LEVEL_CURRENT', 'OIL_LEVEL_MAX', 'OIL_LEVEL_MIN_WARNING',
  'SERVICE_PREDICTIONS',
  'FUEL_LEVEL', 'FUEL_RESERVE',
  'ALARM_STATE', 'THEFT_STATE', 'GLOBAL_PRIVACY_MODE',
  'DEPARTURES', 'TIMERS', 'BLEID_DDADATA', 'PAIRING_CODE',
  'REMOTE_ACCESS_AUTHORIZATION', 'VTS_MODES', 'ACV_STATE',
  'PRED_PRECON_LOCATION_EXCEPTIONS', 'PRED_PRECON_USER_SETTINGS',
] as const;
