#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# This wizard captures no application config, so it keeps its own state file
# rather than writing to the project's .env. All `ask` defaults on a re-run come
# from here.
ENV_FILE="$HOME/.config/porsche-ev-insights/archive-wizard.env"
mkdir -p "$(dirname "$ENV_FILE")"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSPECTOR="$REPO_ROOT/scripts/inspect-porsche-export.py"
ARCHIVED=()

banner "Archive the My Porsche trip CSVs"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Choose where the archive lives"
say "The car's history before today exists in two places: the Porsche API's"
say "rolling window, and the My Porsche app. The window's length is unknown, so"
say "the July-August history may vanish from the API without warning. A CSV"
say "export is the only copy that cannot roll away."
printf '\n'
warn "Not in the git repo: this fork is public, and the export is a dated record"
note "  of when and how far you drove. It goes to a synced folder instead."
printf '\n'

DEFAULT_ARCHIVE="$HOME/Documents/porsche-rittenregistratie"
if [[ -d "$HOME/Library/Mobile Documents/com~apple~CloudDocs" ]]; then
  DEFAULT_ARCHIVE="$HOME/Library/Mobile Documents/com~apple~CloudDocs/porsche-rittenregistratie"
  note "iCloud Drive found — offering it as the default, so the archive survives this Mac."
fi

say "Archive folder [Enter accepts the default]:"
note "  default: $DEFAULT_ARCHIVE"
ask ARCHIVE_ROOT "Path:"
[[ -z "$ARCHIVE_ROOT" ]] && ARCHIVE_ROOT="$DEFAULT_ARCHIVE"
ARCHIVE_ROOT="${ARCHIVE_ROOT/#\~/$HOME}"   # expand a typed ~

if ! mkdir -p "$ARCHIVE_ROOT" 2>/dev/null || [[ ! -w "$ARCHIVE_ROOT" ]]; then
  printf '\n'; warn "cannot write to $ARCHIVE_ROOT — check the path and re-run."
  exit 1
fi
write_env ARCHIVE_ROOT "$ARCHIVE_ROOT"

# A same-day re-run must not overwrite the morning's archive.
STAMP="$(date +%Y-%m-%d)"
ARCHIVE_DIR="$ARCHIVE_ROOT/$STAMP"
_suffix=2
while [[ -e "$ARCHIVE_DIR" ]]; do
  ARCHIVE_DIR="$ARCHIVE_ROOT/$STAMP-$_suffix"
  _suffix=$((_suffix + 1))
done
note "this run archives to: $ARCHIVE_DIR"
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Export 'Since start' from the My Porsche app"
say "This is the file that matters — one row per trip."
printf '\n'
step "Open My Porsche on your phone and select the Taycan."
step "Tap the Trip tab, then scroll to the trip statistics."
step "Choose the Since start statistics."
step "Use the Export / Share option and pick CSV."
printf '\n'
say "Then get the file onto this Mac — whichever is quickest:"
note "  AirDrop to this Mac (lands in ~/Downloads)"
note "  Save to Files → iCloud Drive"
note "  Mail it to yourself and download the attachment"
printf '\n'
note "The file will be named something like"
note "  'Taycan 4 Cross Turismo-Since start-2026-08-22_19-30.csv'"
note "— the app exports in your phone's language, so the name and the column"
note "headers may be Dutch. That is fine; nothing here depends on the language."
printf '\n'
pause "Press Enter once the file is on this Mac"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Export 'Since charge' as well"
say "One row per charge cycle rather than per trip. Optional — it carries no"
say "trip rows, so it is not what the ledger would ever be rebuilt from. It is"
say "cheap to grab while you are already in the app."
printf '\n'
if confirm "Export the Since charge file too?"; then
  step "Same Trip tab, choose the Since charge statistics."
  step "Export as CSV and get it onto this Mac the same way."
  printf '\n'
  pause "Press Enter once that file is on this Mac too"
else
  SKIPPED+=("Since charge export (re-run this wizard to add it)")
  note "skipped — noted in the summary."
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Collect, archive and verify"
say "Looking for recently-modified CSVs in the usual landing places."
printf '\n'

CANDIDATES=()
while IFS= read -r -d '' f; do CANDIDATES+=("$f"); done < <(
  find "$HOME/Downloads" "$HOME/Desktop" "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Downloads" \
       -maxdepth 2 -type f -iname '*.csv' -mtime -2 -print0 2>/dev/null | sort -z
)

SELECTED=()
if (( ${#CANDIDATES[@]} )); then
  say "Found:"
  for i in "${!CANDIDATES[@]}"; do
    printf '  %s%s)%s %s\n' "$BLUE" "$((i + 1))" "$RESET" "${CANDIDATES[$i]}"
  done
  printf '\n'
  say "Enter the numbers to archive, space-separated (or 'a' for all, Enter to"
  say "type paths by hand instead)."
  ask PICK "Numbers:"
  if [[ "$PICK" == "a" || "$PICK" == "A" ]]; then
    SELECTED=("${CANDIDATES[@]}")
  else
    for n in $PICK; do
      [[ "$n" =~ ^[0-9]+$ ]] || continue
      (( n >= 1 && n <= ${#CANDIDATES[@]} )) && SELECTED+=("${CANDIDATES[$((n - 1))]}")
    done
  fi
else
  warn "nothing found automatically — you can still type the paths."
fi

if ! (( ${#SELECTED[@]} )); then
  printf '\n'
  say "Type or drag each CSV in, one per line. Empty line when done."
  while true; do
    printf '  %sPath:%s ' "$BOLD" "$RESET"
    read -r manual || true
    [[ -z "$manual" ]] && break
    manual="${manual%\'}"; manual="${manual#\'}"      # drag-and-drop quoting
    manual="${manual//\\ / }"                          # ...and its escaped spaces
    manual="${manual/#\~/$HOME}"
    if [[ -f "$manual" ]]; then SELECTED+=("$manual"); else warn "no such file: $manual"; fi
  done
fi

if ! (( ${#SELECTED[@]} )); then
  printf '\n'; warn "no files selected — nothing archived. Re-run when the exports are on this Mac."
  exit 1
fi

mkdir -p "$ARCHIVE_DIR"
for src in "${SELECTED[@]}"; do
  dest="$ARCHIVE_DIR/$(basename "$src")"
  cp -p "$src" "$dest"
  ARCHIVED+=("$dest")
  printf '  %s✓ archived%s %s\n' "$GREEN" "$RESET" "$(basename "$src")"
done

printf '\n'
say "Reading what the files actually contain..."
if [[ -x "$INSPECTOR" || -f "$INSPECTOR" ]]; then
  # Tee into a manifest so the archive explains itself years from now.
  /usr/bin/python3 "$INSPECTOR" "${ARCHIVED[@]}" | tee "$ARCHIVE_DIR/MANIFEST.txt"
  {
    printf '\nArchived %s by scripts/archive-porsche-export.sh\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"
    printf 'Source: My Porsche app export (Since start / Since charge)\n'
    printf 'Context: github.com/jreijnders/porsche_ev_insights issue #6\n'
  } >> "$ARCHIVE_DIR/MANIFEST.txt"
  note "manifest written to $ARCHIVE_DIR/MANIFEST.txt"
else
  SKIPPED+=("inspection — $INSPECTOR not found")
  warn "inspector missing; files are archived but unverified."
fi

printf '\n'
say "Record the row count and date range above on issue #6 — the row count is"
say "also an independent check on how far the API's own history reaches."

finish
