#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Google Maps Platform — key for the rittenregistratie"

# ── 1. A dedicated project ────────────────────────────────────────────────
stage "Create a dedicated Google Cloud project"
say "A project of its own keeps quota, spend and the key isolated — and lets you"
say "revoke everything later by deleting one thing."
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: porsche-rittenregistratie (or anything you like)."
step "Leave the organisation/location as offered."
step "Click CREATE, then wait for it to become the selected project."
note "The console UI shifts around; if a label differs, follow the intent, not the wording."
ask GOOGLE_CLOUD_PROJECT "Paste the Project ID (not the name — the id under it):"
write_env GOOGLE_CLOUD_PROJECT "$GOOGLE_CLOUD_PROJECT"

# ── 2. Billing, and the EEA question ──────────────────────────────────────
stage "Attach billing — and check the country"
say "Places needs billing attached even though we expect to spend nothing."
say ""
warn "This stage decides which Terms of Service govern the place book."
say "The whole storage design rests on Google's EEA terms: place_id may be kept"
say "indefinitely, but names and addresses may not be cached at all. If this"
say "billing account is NOT in the EEA, a different set of terms applies and the"
say "design needs revisiting before any place data is stored."
open_url "https://console.cloud.google.com/billing"
step "Link a billing account to the project you just created."
step "Open the billing account, then look at its country / payments profile."
ask GOOGLE_BILLING_COUNTRY "Which country is the billing account registered in?"
write_env GOOGLE_BILLING_COUNTRY "$GOOGLE_BILLING_COUNTRY"
if ! confirm "Is that country in the EEA (EU + Iceland, Liechtenstein, Norway)?"; then
  warn "Non-EEA billing account — STOP and re-check the terms analysis."
  warn "Record this on the ticket before storing any Google place data."
  SKIPPED+=("Re-check Google terms: billing account is outside the EEA")
  confirm "Continue anyway (you can still create the key)?" || { finish; exit 0; }
fi

# ── 3. Enable the API ─────────────────────────────────────────────────────
stage "Enable Places API (New)"
say "Only the New API — its IDs-Only SKUs are the free ones that make this cost"
say "nothing. The legacy API is deliberately left off."
open_url "https://console.cloud.google.com/apis/library/places.googleapis.com?project=${GOOGLE_CLOUD_PROJECT}"
step "Confirm the project selector shows ${GOOGLE_CLOUD_PROJECT}."
step "Click ENABLE. If it already says MANAGE, it is enabled."
pause "Enabled? Press Enter."

# ── 4. Create and restrict the key ────────────────────────────────────────
stage "Create the API key and restrict it"
open_url "https://console.cloud.google.com/apis/credentials?project=${GOOGLE_CLOUD_PROJECT}"
step "CREATE CREDENTIALS → API key. Copy it when the dialog shows it."
step "Then open the new key to edit it:"
step "  Application restrictions → None."
note "  Deliberate: your server's home IP can change, and an IP lock failing"
note "  looks like broken geocoding rather than an expired restriction."
step "  API restrictions → Restrict key → select ONLY 'Places API (New)'."
step "SAVE. Restrictions can take a minute or two to take effect."
ask_secret GOOGLE_MAPS_API_KEY "Paste the API key:"
# Sanity-check the shape before spending a request on it. A double-paste is
# easy to do with a hidden prompt and otherwise shows up as the unhelpful
# "API key not valid", which sends you hunting in the console for nothing.
while [[ -n "${GOOGLE_MAPS_API_KEY}" ]]; do
  _len=${#GOOGLE_MAPS_API_KEY}
  if [[ "${GOOGLE_MAPS_API_KEY}" != AIza* ]]; then
    warn "That does not look like a Google API key (they start with AIza)."
  elif (( _len == 78 )) && [[ "${GOOGLE_MAPS_API_KEY:0:39}" == "${GOOGLE_MAPS_API_KEY:39:39}" ]]; then
    warn "That is the same key pasted twice ($_len chars) — trimming to 39."
    GOOGLE_MAPS_API_KEY="${GOOGLE_MAPS_API_KEY:0:39}"
    break
  elif (( _len != 39 )); then
    warn "Expected 39 characters, got $_len — check for a stray paste or space."
  else
    break
  fi
  ask_secret GOOGLE_MAPS_API_KEY "Paste the API key again (or Enter to skip):"
  [[ -z "${GOOGLE_MAPS_API_KEY}" ]] && break
done
if [[ -z "${GOOGLE_MAPS_API_KEY}" ]]; then
  warn "No key entered — nothing to verify."
  SKIPPED+=("GOOGLE_MAPS_API_KEY (re-run this wizard)")
  finish
  exit 0
fi
write_env GOOGLE_MAPS_API_KEY "$GOOGLE_MAPS_API_KEY"
note "Written to .env, which is gitignored. It never enters the repo."

# ── 5. Prove it works ─────────────────────────────────────────────────────
stage "Verify with a live Places call"
say "One Text Search asking for place ids only — the free SKU. This proves the"
say "key is valid, the API is enabled, the restriction is right, and billing is live."
say ""
RESPONSE_FILE=$(mktemp)
HTTP_CODE=$(curl -sS -o "$RESPONSE_FILE" -w '%{http_code}' \
  -X POST "https://places.googleapis.com/v1/places:searchText" \
  -H "Content-Type: application/json" \
  -H "X-Goog-Api-Key: ${GOOGLE_MAPS_API_KEY}" \
  -H "X-Goog-FieldMask: places.id" \
  -d '{"textQuery":"Amsterdam Centraal","maxResultCount":2}' 2>/dev/null || echo "000")

PLACE_IDS=$(python3 - "$RESPONSE_FILE" <<'PYEOF' 2>/dev/null || true
import json, sys
try:
    data = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(1)
print(" ".join(p.get("id", "") for p in data.get("places", [])))
PYEOF
)
ERROR_MSG=$(python3 - "$RESPONSE_FILE" <<'PYEOF' 2>/dev/null || true
import json, sys
try:
    data = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(1)
err = data.get("error", {})
print(err.get("message", "") or err.get("status", ""))
PYEOF
)

if [[ "$HTTP_CODE" == "200" && -n "${PLACE_IDS// /}" ]]; then
  printf '  %s✓ verified%s HTTP 200, place ids returned: %s\n' "$GREEN" "$RESET" "$PLACE_IDS"
  say ""
  say "Note what came back: place ids and nothing else. That is the shape the place"
  say "book stores — your own coordinate, your own label, and this id. Names and"
  say "addresses are re-fetched on demand, never cached."
else
  warn "Verification failed — HTTP $HTTP_CODE"
  [[ -n "$ERROR_MSG" ]] && note "Google said: $ERROR_MSG"
  say ""
  say "Most likely causes, in the order worth checking:"
  case "$ERROR_MSG" in
    *"has not been used"*|*"is disabled"*|*SERVICE_DISABLED*)
      step "Places API (New) is not enabled on ${GOOGLE_CLOUD_PROJECT} — redo stage 3." ;;
    *"API_KEY_SERVICE_BLOCKED"*|*"not authorized"*|*"blocked"*)
      step "The key's API restriction excludes Places API (New) — redo stage 4." ;;
    *"API key not valid"*|*"API_KEY_INVALID"*)
      step "The key was mistyped or belongs to another project — redo stage 4." ;;
    *billing*|*BILLING*)
      step "Billing is not active on the project — redo stage 2." ;;
    *)
      step "Restrictions can take a couple of minutes to propagate — wait, then re-run."
      step "Otherwise check the project selector matched ${GOOGLE_CLOUD_PROJECT} throughout." ;;
  esac
  SKIPPED+=("Verify the key: re-run this wizard once the cause above is fixed")
fi
rm -f "$RESPONSE_FILE"

say ""
say "Record on the ticket (Provision a Google Maps Platform API key):"
note "  project:      ${GOOGLE_CLOUD_PROJECT}"
note "  billing:      ${GOOGLE_BILLING_COUNTRY}"
note "  APIs enabled: Places API (New) only"
note "  restrictions: application None, API restricted to Places API (New)"
note "  spend guard:  none — free IDs-Only SKUs; budget enforced in app code"
note "  key location: .env (gitignored), reaches the container via compose"

finish
